CREATE TABLE gank_posts (
  _id VARCHAR(56) NOT NULL PRIMARY KEY,
	day VARCHAR(56) NOT NULL,
	type VARCHAR(56) NOT NULL,
	description TEXT NOT NULL,
	url VARCHAR(1024) NOT NULL,
	createdAt VARCHAR(56),
	publishedAt VARCHAR(56),
	who VARCHAR(56),
	_ns VARCHAR(56)
  );